import type { IExerciseShort } from './types'

export const mockExercises: IExerciseShort[] = [
	{
		id: 1,
		title: 'название 1',
		description: 'Выбор ответа(ов)',
		type: 'choice',
		difficulty: 'easy',
		is_active: true,
		created_at: '2024-01-15T10:00:00Z',
	},
	{
		id: 2,
		title: 'название 2',
		description: 'Ручной ввод ответа',
		type: 'input',
		difficulty: 'medium',
		is_active: true,
		created_at: '2024-01-16T14:30:00Z',
	},
	{
		id: 3,
		title: 'название 3',
		description: 'Сортировка',
		type: 'ordering',
		difficulty: 'hard',
		is_active: true,
		created_at: '2024-01-17T09:15:00Z',
	},
	{
		id: 4,
		title: 'название 4',
		description: 'Сопоставление',
		type: 'matching',
		difficulty: 'easy',
		is_active: false,
		created_at: '2024-01-18T16:45:00Z',
	},
	{
		id: 5,
		title: 'название 5',
		description: 'Группировка',
		type: 'grouping',
		difficulty: 'medium',
		is_active: true,
		created_at: '2024-01-19T11:20:00Z',
	},
	{
		id: 6,
		title: 'название 6',
		description: 'Графическое задание',
		type: 'drawing',
		difficulty: 'hard',
		is_active: true,
		created_at: '2024-01-20T08:00:00Z',
	},
]
