import type React from 'react'
import styles from './styles.module.css'
import type { TLevelIndicatorProps } from './types'

// Верхняя граница допустимого значения
// взята из типа TMaxLevel
// переменная и проверки нужны, если значения будут приходить из API,
// чтобы не упал код в рантайме
const MAX_SCALE = 10

// отключено правила линтера т.к.
// контекст делает использование индекса в роле ключа безопасным

export const LevelIndicator: React.FC<TLevelIndicatorProps> = ({
	maxLevel,
	currentLevel,
	icon: Icon,
}) => {
	const safeMaxLevel = Math.min(Math.max(maxLevel, 1), MAX_SCALE)
	const safeCurrentLevel = Math.min(Math.max(currentLevel, 1), safeMaxLevel)

	return (
		<div className={styles.wrapper}>
			{Array.from({ length: safeMaxLevel }).map((_, index) => {
				const isActive = index < safeCurrentLevel

				return (
					<Icon
						// biome-ignore lint/suspicious/noArrayIndexKey: icons are generated by position
						key={index}
						className={isActive ? styles.active : styles.inactive}
					/>
				)
			})}
		</div>
	)
}
